### ISSUE TITLE
什么垃圾

### ISSUE THREAD

**Issue by qiuquanwu** [linlianmin/laravel-vue#14]
垃圾东西，一堆错误。别放上来了

**Comment by linlianmin** [comment]
基本排错都不会，你不适合干这个。另外，你家人是否健在还是已故，没家教的东西，替我问候你老母发自我的iPhone------------------ 原始邮件 ------------------发件人: 邱权武  <notifications@github.com>发送时间: 2018年4月20日 12:07收件人: linlianmin/laravel-vue <laravel-vue@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[linlianmin/laravel-vue] 什么垃圾 (#14)垃圾东西，一堆错误。别放上来了

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linlianmin/laravel-vue","title":"linlianmin/laravel-vue","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linlianmin/laravel-vue"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"什么垃圾 (#14)"}],"action":{"name":"View Issue","url":"https://github.com/linlianmin/laravel-vue/issues/14"}}}
